# ***What is NumPy?***



It is a python library that supports multidimensional arrays and matrices, allows us to perform high-level mathematical operations on these arrays and works fast. It is used very often in data analysis.

In [ ]:
import numpy as np

# ****The Basics****

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b = np.array([1,2,3,'Hello World'])
print(b)

['1' '2' '3' 'Hello World']


In [ ]:
skaler = np.array(91)
print(skaler)

91


In [ ]:
vektor = np.array([91,92,93,94,95,96,97,98,99])
print(vektor)

[91 92 93 94 95 96 97 98 99]


In [ ]:
matris = np.array([[91,92,93],[94,95,96],[97,98,99]])
print(matris)

[[91 92 93]
 [94 95 96]
 [97 98 99]]


In [ ]:
tensor = np.array([[[91,92,93],[94,95,96],[97,98,99]],[[91,92,93],[94,95,96],[97,98,99]],[[91,92,93],[94,95,96],[97,98,99]]])
print(tensor)

[[[91 92 93]
  [94 95 96]
  [97 98 99]]

 [[91 92 93]
  [94 95 96]
  [97 98 99]]

 [[91 92 93]
  [94 95 96]
  [97 98 99]]]


# ***INDEX***

In [ ]:
vektor = np.array([55,56,57,58,59,60])
print(vektor)

[55 56 57 58 59 60]


In [ ]:
vektor[3]

58

In [ ]:
vektor[1]

56

In [ ]:
vektor[0]

55

In [ ]:
vektor[-1]

60

# ***SLICE***

In [ ]:
vektor[1:5]

array([56, 57, 58, 59])

In [ ]:
vektor[2:4]

array([57, 58])

In [ ]:
vektor[:5]

array([55, 56, 57, 58, 59])

In [ ]:
vektor[4:]

array([59, 60])

In [ ]:
vektor[1:5:2]

array([56, 58])

# ***SIZE***

In [ ]:
vektor1 = np.array([1,2,3,4,5,6,7,8,9])
print(vektor)

[1 2 3 4 5 6 7 8 9]


In [ ]:
matris1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matris1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
vektor1.size  #returns the number of elements

9

In [ ]:
matris1.size

12

# ***SHAPE***

In [ ]:
vektor1.shape  #shows how many values are in each dimension

(9,)

In [ ]:
matris1.shape

(3, 3)

# ***NDIM***

In [ ]:
vektor1.ndim     #gives how many dimensions

1

In [ ]:
matris1.ndim

2

# ***DTYPE***

In [ ]:
vektor.dtype  #indicates the data type

dtype('int64')

In [ ]:
matris.dtype

dtype('int64')

# ***CHANGE NUMPY DATA TYPE***

In [ ]:
sayilar = np.array([1,2,3,4,5.0,6])
print(sayilar)

[1. 2. 3. 4. 5. 6.]


In [ ]:
sayilar.dtype

dtype('float64')

In [ ]:
sayilar = sayilar.astype("int64")

In [ ]:
sayilar.dtype

dtype('int64')

In [ ]:
sayilar2 = np.array([1.2,2.3,4.5,6.8])
print(sayilar2)

[1.2 2.3 4.5 6.8]


In [ ]:
sayilar2.dtype

dtype('float64')

In [ ]:
sayilar2 = sayilar2.astype("int32")

In [ ]:
sayilar2.dtype

dtype('int32')

In [ ]:
sayilar3 = np.array([1,2,3,1.5,8,9.5], dtype="int16")
print(sayilar3)

[1 2 3 1 8 9]


In [ ]:
sayilar3.dtype

dtype('int16')

# ***SLICE IN MATRICES***

In [ ]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matris[0][1]

2

In [ ]:
matris[1]

array([4, 5, 6])

In [ ]:
matris[-1]

array([7, 8, 9])

In [ ]:
matris[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matris[0,:3]

array([1, 2, 3])

In [ ]:
matris[0:3,0:1]

array([[1],
       [4],
       [7]])

# ***RANDOM MATRIX CREATION***

In [ ]:
np.random.randint(0,20)

7

In [ ]:
np.random.randint(23,100)

90

In [ ]:
np.random.randint(0,300,(6,6))

array([[225,  99, 297, 193, 256,  82],
       [ 27,  81, 143,  19, 206,  73],
       [166,  59, 218,  48,  74,  93],
       [219, 270, 279,  85,  27, 228],
       [121, 251,  35, 102,   9, 284],
       [102, 272, 158, 271, 263,  21]])

In [ ]:
np.random.randint(0,38,(3,3))

array([[ 5, 37,  8],
       [13,  9, 32],
       [34, 37, 20]])

# ***VECTOR CREATION WITH ARANGE***

In [ ]:
a = np.arange(100)


In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(10,40)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
np.arange(1.8,39.3,3)

array([ 1.8,  4.8,  7.8, 10.8, 13.8, 16.8, 19.8, 22.8, 25.8, 28.8, 31.8,
       34.8, 37.8])

# ***LINSPACE***

In [ ]:
np.linspace(0,50,12)

array([ 0.        ,  4.54545455,  9.09090909, 13.63636364, 18.18181818,
       22.72727273, 27.27272727, 31.81818182, 36.36363636, 40.90909091,
       45.45454545, 50.        ])

In [ ]:
np.linspace(20,200,10)

array([ 20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.])

# ***RESHAPE***

In [ ]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
b.shape

(4, 5)

In [ ]:
b.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# ***COPY***

In [ ]:
matris = np.random.randint(0,10,(5,4))

In [ ]:
matris

array([[4, 6, 2, 8],
       [9, 7, 9, 9],
       [4, 6, 8, 5],
       [1, 0, 8, 1],
       [6, 3, 0, 9]])

In [ ]:
matris1 = matris.copy()

In [ ]:
matris1

array([[4, 6, 2, 8],
       [9, 7, 9, 9],
       [4, 6, 8, 5],
       [1, 0, 8, 1],
       [6, 3, 0, 9]])

# ***VIEW***

In [ ]:
matris2 = np.random.randint(10,80,(7,6))

In [ ]:
matris2

array([[22, 40, 69, 12, 33, 57],
       [76, 67, 54, 34, 24, 21],
       [17, 30, 43, 62, 10, 73],
       [65, 65, 69, 57, 64, 58],
       [21, 61, 60, 54, 66, 21],
       [73, 20, 24, 76, 12, 66],
       [17, 25, 46, 14, 14, 13]])

In [ ]:
matris3 = matris2.view()

In [ ]:
matris3

array([[22, 40, 69, 12, 33, 57],
       [76, 67, 54, 34, 24, 21],
       [17, 30, 43, 62, 10, 73],
       [65, 65, 69, 57, 64, 58],
       [21, 61, 60, 54, 66, 21],
       [73, 20, 24, 76, 12, 66],
       [17, 25, 46, 14, 14, 13]])

In [ ]:
matris3[0]= [10,10,11,12,15,18]

In [ ]:
matris3

array([[10, 10, 11, 12, 15, 18],
       [76, 67, 54, 34, 24, 21],
       [17, 30, 43, 62, 10, 73],
       [65, 65, 69, 57, 64, 58],
       [21, 61, 60, 54, 66, 21],
       [73, 20, 24, 76, 12, 66],
       [17, 25, 46, 14, 14, 13]])

# ***ZEROS***

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((10,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

# ***ONES***

In [ ]:
np.ones(11)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(shape= (2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

# ***FULL***

In [ ]:
np.full((7,5),21)

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

# ***IDENTITY***

In [ ]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

# ***EYE***

In [ ]:
np.eye(8,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.eye(11,k=8)

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# ***DIAG***

In [ ]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag([1,1,2,2,3,3,4,4])

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 4]])

# ***MATHEMATICAL OPERATIONS***

In [ ]:
a = np.ones((4,4), dtype="int16")
b = np.full((4,4),12, dtype="int16")

In [ ]:
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
b

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]], dtype=int16)

In [ ]:
a*8

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]], dtype=int16)

In [ ]:
b+3

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]], dtype=int16)

In [ ]:
a+b

array([[13, 13, 13, 13],
       [13, 13, 13, 13],
       [13, 13, 13, 13],
       [13, 13, 13, 13]], dtype=int16)

In [ ]:
b-a

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]], dtype=int16)

In [ ]:
a/4

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [ ]:
b/8

array([[1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5]])

In [ ]:
a//2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [ ]:
b//2

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]], dtype=int16)

In [ ]:
b%5

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]], dtype=int16)

In [ ]:
a%2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
exa = np.array([8,9,10])
exa

array([ 8,  9, 10])

In [ ]:
exa+5

array([13, 14, 15])

In [ ]:
exa*8

array([64, 72, 80])

In [ ]:
exa/7

array([1.14285714, 1.28571429, 1.42857143])

In [ ]:
exa//7

array([1, 1, 1])

In [ ]:
exa%4

array([0, 1, 2])

In [ ]:
exa-5

array([3, 4, 5])

In [ ]:
exa1 = np.ones((5,5), dtype="int32")

In [ ]:
exa1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
exa2 = np.ones((4,4), dtype="int32")

In [ ]:
exa2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [ ]:
exa1.reshape(25)[:16].reshape(4,4)+exa2

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]], dtype=int32)

In [ ]:
exa1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
exa1[0] = exa[0]*3

In [ ]:
exa1

array([[24, 24, 24, 24, 24],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1]], dtype=int32)

In [ ]:
np.cos(exa1)

array([[0.42417901, 0.42417901, 0.42417901, 0.42417901, 0.42417901],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231, 0.54030231]])

In [ ]:
np.cos(exa2)

array([[0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231, 0.54030231]])

# ***LOGICAL OPERATORS***

In [ ]:
matris = np.random.randint(0,20,(4,4))

In [ ]:
matris

array([[ 4,  3, 18, 11],
       [ 7,  3, 17, 16],
       [ 7, 11,  9,  4],
       [11,  2,  1, 14]])

In [ ]:
matris>10

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [ ]:
matris[matris>10]

array([18, 11, 17, 16, 11, 11, 14])

In [ ]:
matris[matris<10]

array([4, 3, 7, 3, 7, 9, 4, 2, 1])

In [ ]:
matris[matris>=10]

array([18, 11, 17, 16, 11, 11, 14])

In [ ]:
matris[matris==10]

array([], dtype=int64)

In [ ]:
matris[matris==17]

array([17])

In [ ]:
matris[matris==11].size

3

In [ ]:
matris[matris!=11]

array([ 4,  3, 18,  7,  3, 17, 16,  7,  9,  4,  2,  1, 14])

In [ ]:
matris[matris!=11].size

13

In [ ]:
matris%2==0

array([[ True, False,  True, False],
       [False, False, False,  True],
       [False, False, False,  True],
       [False,  True, False,  True]])

In [ ]:
a = matris == 9

In [ ]:
b = matris%3==0

In [ ]:
matris[a]

array([9])

In [ ]:
matris[b]

array([ 3, 18,  3,  9])

In [ ]:
matris[a&b]

array([9])

In [ ]:
matris[a | b]

array([ 3, 18,  3,  9])

In [89]:
np.subtract(matris,1)

array([[ 3,  2, 17, 10],
       [ 6,  2, 16, 15],
       [ 6, 10,  8,  3],
       [10,  1,  0, 13]])

In [90]:
np.mean(matris)

8.625

In [91]:
np.sum(matris)

138

In [92]:
np.max(matris)

18

In [93]:
np.min(matris)

1

In [94]:
np.var(matris)

29.484375

In [95]:
np.add(matris,1)

array([[ 5,  4, 19, 12],
       [ 8,  4, 18, 17],
       [ 8, 12, 10,  5],
       [12,  3,  2, 15]])